[
  {
    "table_name": "closing_stock_items",
    "trigger_name": "trg_after_closing_stock_insert",
    "function_name": "fn_after_closing_stock_insert",
    "trigger_definition": "CREATE TRIGGER trg_after_closing_stock_insert AFTER INSERT ON closing_stock_items FOR EACH ROW EXECUTE FUNCTION fn_after_closing_stock_insert()",
    "function_body": "CREATE OR REPLACE FUNCTION public.fn_after_closing_stock_insert()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$DECLARE\r\n  v_tx_date       date;\r\n  v_item_name     varchar;\r\n  v_opening_qty   numeric := 0;\r\n  v_prev_closing  numeric;\r\n  v_prev_date     date;\r\n  v_next_ledger   date;\r\nBEGIN\r\n  -- 1. Get transaction date\r\n  SELECT transaction_date\r\n    INTO v_tx_date\r\n    FROM public.inventory_transactions\r\n   WHERE id = NEW.transaction_id;\r\n\r\n  -- 2. Get item name\r\n  SELECT item_name\r\n    INTO v_item_name\r\n    FROM public.items\r\n   WHERE id = NEW.item_id;\r\n\r\n  -- 3. Find closest previous ledger row\r\n  SELECT\r\n      closing_qty,\r\n      ledger_date\r\n    INTO\r\n      v_prev_closing,\r\n      v_prev_date\r\n    FROM public.stock_ledger\r\n   WHERE item_id = NEW.item_id\r\n     AND ledger_date < v_tx_date\r\n   ORDER BY ledger_date DESC\r\n   LIMIT 1;\r\n\r\n  -- 4. Determine opening quantity\r\n  IF v_prev_closing IS NOT NULL THEN\r\n      -- Use previous day's closing\r\n      v_opening_qty := v_prev_closing;\r\n  ELSE\r\n      -- Previous day's closing not entered yet\r\n      -- Use current stock from items table\r\n      SELECT COALESCE(current_stock, 0)\r\n        INTO v_opening_qty\r\n        FROM public.items\r\n       WHERE id = NEW.item_id;\r\n  END IF;\r\n\r\n  -- 5. Upsert ledger row\r\n  INSERT INTO public.stock_ledger\r\n    (\r\n      item_id,\r\n      item_name,\r\n      ledger_date,\r\n      date_for_opening,\r\n      opening_qty,\r\n      purchase_qty,\r\n      closing_qty\r\n    )\r\n  VALUES\r\n    (\r\n      NEW.item_id,\r\n      v_item_name,\r\n      v_tx_date,\r\n      v_prev_date,\r\n      v_opening_qty,\r\n      0,\r\n      NEW.total_qty\r\n    )\r\n  ON CONFLICT (item_id, ledger_date)\r\n  DO UPDATE SET\r\n    closing_qty      = EXCLUDED.closing_qty,\r\n    item_name        = EXCLUDED.item_name,\r\n    opening_qty      = CASE\r\n                         WHEN stock_ledger.opening_qty = 0\r\n                         THEN EXCLUDED.opening_qty\r\n                         ELSE stock_ledger.opening_qty\r\n                       END,\r\n    date_for_opening = CASE\r\n                         WHEN stock_ledger.opening_qty = 0\r\n                         THEN EXCLUDED.date_for_opening\r\n                         ELSE stock_ledger.date_for_opening\r\n                       END,\r\n    updated_at       = now();\r\n\r\n  -- 6. Update next ledger row opening quantity\r\n  SELECT MIN(ledger_date)\r\n    INTO v_next_ledger\r\n    FROM public.stock_ledger\r\n   WHERE item_id = NEW.item_id\r\n     AND ledger_date > v_tx_date;\r\n\r\n  IF v_next_ledger IS NOT NULL THEN\r\n    UPDATE public.stock_ledger\r\n       SET opening_qty      = NEW.total_qty,\r\n           date_for_opening = v_tx_date,\r\n           updated_at       = now()\r\n     WHERE item_id = NEW.item_id\r\n       AND ledger_date = v_next_ledger;\r\n  END IF;\r\n\r\n  RETURN NEW;\r\nEND;$function$\n"
  },
  {
    "table_name": "closing_stock_items",
    "trigger_name": "trg_sync_current_stock_closing",
    "function_name": "fn_sync_current_stock",
    "trigger_definition": "CREATE TRIGGER trg_sync_current_stock_closing AFTER INSERT OR DELETE OR UPDATE ON closing_stock_items FOR EACH ROW EXECUTE FUNCTION fn_sync_current_stock()",
    "function_body": "CREATE OR REPLACE FUNCTION public.fn_sync_current_stock()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  IF TG_OP = 'DELETE' THEN\r\n    UPDATE public.items\r\n       SET current_stock = public.fn_recalculate_current_stock(OLD.item_id)\r\n     WHERE id = OLD.item_id;\r\n    RETURN OLD;\r\n  ELSE\r\n    UPDATE public.items\r\n       SET current_stock = public.fn_recalculate_current_stock(NEW.item_id)\r\n     WHERE id = NEW.item_id;\r\n    RETURN NEW;\r\n  END IF;\r\nEND;\r\n$function$\n"
  },
  {
    "table_name": "purchase_items",
    "trigger_name": "trg_after_purchase_item_insert",
    "function_name": "fn_after_purchase_item_insert",
    "trigger_definition": "CREATE TRIGGER trg_after_purchase_item_insert AFTER INSERT ON purchase_items FOR EACH ROW EXECUTE FUNCTION fn_after_purchase_item_insert()",
    "function_body": "CREATE OR REPLACE FUNCTION public.fn_after_purchase_item_insert()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$DECLARE\r\n  v_tx_date       date;\r\n  v_item_name     varchar;\r\n  v_opening_qty   numeric := 0;\r\n  v_prev_closing  numeric;\r\n  v_prev_date     date;\r\nBEGIN\r\n  -- 1. Get transaction date\r\n  SELECT transaction_date\r\n    INTO v_tx_date\r\n    FROM public.inventory_transactions\r\n   WHERE id = NEW.transaction_id;\r\n\r\n  -- 2. Get item name\r\n  SELECT item_name\r\n    INTO v_item_name\r\n    FROM public.items\r\n   WHERE id = NEW.item_id;\r\n\r\n  -- 3. Find the most recent closing_qty for this item BEFORE this date\r\n  SELECT closing_qty, ledger_date\r\n    INTO v_prev_closing, v_prev_date\r\n    FROM public.stock_ledger\r\n   WHERE item_id = NEW.item_id\r\n     AND ledger_date < v_tx_date\r\n   ORDER BY ledger_date DESC\r\n   LIMIT 1;\r\n\r\n  -- 4. Opening qty = previous closing.\r\n  --    If no previous closing exists, use current_stock from items.\r\n  IF v_prev_closing IS NULL THEN\r\n    SELECT current_stock\r\n      INTO v_opening_qty\r\n      FROM public.items\r\n     WHERE id = NEW.item_id;\r\n  ELSE\r\n    v_opening_qty := v_prev_closing;\r\n  END IF;\r\n\r\n  -- 5. Upsert ledger row\r\n  INSERT INTO public.stock_ledger\r\n    (\r\n      item_id,\r\n      item_name,\r\n      ledger_date,\r\n      date_for_opening,\r\n      opening_qty,\r\n      purchase_qty\r\n    )\r\n  VALUES\r\n    (\r\n      NEW.item_id,\r\n      v_item_name,\r\n      v_tx_date,\r\n      v_prev_date,\r\n      v_opening_qty,\r\n      NEW.quantity\r\n    )\r\n  ON CONFLICT (item_id, ledger_date)\r\n  DO UPDATE SET\r\n    purchase_qty = stock_ledger.purchase_qty + EXCLUDED.purchase_qty,\r\n    item_name    = EXCLUDED.item_name,\r\n    updated_at   = now();\r\n\r\n  RETURN NEW;\r\nEND;$function$\n"
  },
  {
    "table_name": "purchase_items",
    "trigger_name": "trg_sync_current_stock_purchase",
    "function_name": "fn_sync_current_stock",
    "trigger_definition": "CREATE TRIGGER trg_sync_current_stock_purchase AFTER INSERT OR DELETE OR UPDATE ON purchase_items FOR EACH ROW EXECUTE FUNCTION fn_sync_current_stock()",
    "function_body": "CREATE OR REPLACE FUNCTION public.fn_sync_current_stock()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  IF TG_OP = 'DELETE' THEN\r\n    UPDATE public.items\r\n       SET current_stock = public.fn_recalculate_current_stock(OLD.item_id)\r\n     WHERE id = OLD.item_id;\r\n    RETURN OLD;\r\n  ELSE\r\n    UPDATE public.items\r\n       SET current_stock = public.fn_recalculate_current_stock(NEW.item_id)\r\n     WHERE id = NEW.item_id;\r\n    RETURN NEW;\r\n  END IF;\r\nEND;\r\n$function$\n"
  },
  {
    "table_name": "stock_ledger",
    "trigger_name": "trg_stock_ledger_updated_at",
    "function_name": "fn_set_stock_ledger_updated_at",
    "trigger_definition": "CREATE TRIGGER trg_stock_ledger_updated_at BEFORE UPDATE ON stock_ledger FOR EACH ROW EXECUTE FUNCTION fn_set_stock_ledger_updated_at()",
    "function_body": "CREATE OR REPLACE FUNCTION public.fn_set_stock_ledger_updated_at()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  NEW.updated_at = now();\r\n  RETURN NEW;\r\nEND;\r\n$function$\n"
  }
]